channels:

  - conda-forge

dependencies:

  - python=3.10
  - pip
  - nodejs
  - pip:
      - robocorp
      - robocorp-browser
      - langchain
      - langchain-openai
      - python-dotenv
      - pandas
